const PATTERN_1 = [
  [
    {"color": "RED", "revealed": true, "word": ""},
     {"color": "WHITE", "revealed": true, "word": ""},
      {"color": "RED", "revealed": true, "word": ""},
       {"color": "WHITE", "revealed": true, "word": ""},
        {"color": "BLUE", "revealed": true, "word": ""}],
         [{"color": "RED", "revealed": true, "word": ""},
           {"color": "BLUE", "revealed": true, "word": ""},
            {"color": "WHITE", "revealed": true, "word": ""},
             {"color": "WHITE", "revealed": true, "word": ""},
              {"color": "BLUE", "revealed": true, "word": ""}],
               [{"color": "BLUE", "revealed": true, "word": ""},
                 {"color": "RED", "revealed": true, "word": ""},
                  {"color": "BLUE", "revealed": true, "word": ""},
                   {"color": "WHITE", "revealed": true, "word": ""},
                    {"color": "RED", "revealed": true, "word": ""}],
                     [{"color": "RED", "revealed": true, "word": ""},
                       {"color": "RED", "revealed": true, "word": ""},
                        {"color": "BLACK", "revealed": true, "word": ""},
                         {"color": "BLUE", "revealed": true, "word": ""},
                          {"color": "RED", "revealed": true, "word": ""}],
                           [{"color": "BLUE", "revealed": true, "word": ""},
                             {"color": "RED", "revealed": true, "word": ""},
                              {"color": "BLUE", "revealed": true, "word": ""},
                               {"color": "WHITE", "revealed": true, "word": ""},
                                {"color": "WHITE", "revealed": true, "word": ""}]]
